app:
  name: 'library'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'library'

postgres:
  PG_URL: postgresql://postgres:root@localhost:5432/library?sslmode=disable